### ISSUE TITLE
No <lb> elements in jHeading.dita

### ISSUE THREAD

**Issue by nolda** [deutschestextarchiv/dtabf#72]
In the example given in jHeading.dita, there are no <lb> elements. Although, strictly speaking, they are not required here since this example is an abstract schema, unrelated to any specific source, the example may be misleading without such.
It might be a good idea, then, to add a comment that normally, <lb> elements would be added wherever there is a linebreak in the source.

**Comment by susannehaaf** [comment]
The problem here is, that this is indeed not a real-life example but rather a demonstration of the encoding described in the chapter. Thus, we don't know where the linebreaks would be. The usage of linebreaks in DTABf is described here: http://deutschestextarchiv.de/doku/basisformat/lbAllg.html where it says: "Jeder Zeilenschluß wird durch das leere Element `<lb/>` gekennzeichnet. Dieses ist grundsätzlich in keinem Element implizit, sondern wird immer explizit gesetzt. Allein die Elemente `<pb>`, `<cb>`, und `<space>` stehen ohne folgendes `<lb>`-Element."

I'm not sure about a comment on the linebreaks issue here because for conformity reasons it would then be necessary to add such comment to quite some topics of the documentation. 

The problem might rather be solved by adding a real-world example to this chapter.

**Comment by susannehaaf** [comment]
Done (will be visible shortly).
